name: PvPCore
main: jkorn\pvpcore\PvPCore
version: 1.0.0
api: "3.0.0"
author: jkorn
description: A plugin that edits the knockback of the player.

permissions:
  pvpcore.permission.edit:
    description: "Permission for using the PvPCore menu."
    default: op