name: PvPCore
author: "jkorn"
main: pvpcore.PvPCore
version: 2.0.2
website: "https://github.com/jkorn2324"
api: ["1.0.0"]
description: A plugin that edits the knockback taken by players.

permissions:
  pvpcore.permission.edit:
    default: op
    description: "Permission for using the PvPCore menu."
