# The death message that appears when a player is killed by another player.
# Parameters:
# %player-x% = The player that died.
# %player-y% = The player that killed the other player.
death-message: "%player-x% has been memed by %player-y%!"

# This allows the player to toggle and set the knockback for each level on the
# server. This part of the config updates every minute, constantly updating
# the knockback of the levels, and adding new levels in the server to the
# levels list.
#
# How to configure the knockback:
#
# knockback-y: Toggles how high the knockback is.
#              - Default Value: 0.4
# knockback-xz: Toggles how large the horizontal knockback is.
#              - Default Value: 0.4
# customkb: Determines whether the default Nukkit kb is used for that particular
#           level or whether you are configuring your custom kb. (Set to true to
#           enable.
#              - Default Value: false
# worldtype: Determines the type of knockback for the world. The valid level kb-types
#            are: 'default' and 'combo'
#              - Default Value: default
levels:
